<?xml version="1.0"?>
<package format="3">
    <name>ardupilot_deadreckoning</name>
    <version>0.1.0</version>
    <description>ArduPilot Dead Reckoning</description>

    <maintainer email="abhishekchoithani24@gmail.com">Abhishek Choithani</maintainer>
    <license>LGPLv3</license>

    <author email="abhishekchoithani24@gmail.com">Abhishek Choithani</author>

    <buildtool_depend condition="$ROS_VERSION == 1">colcon</buildtool_depend>
    <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

    <depend>plotjuggler</depend>

    <!-- The export tag contains other, unspecified, tags -->
    <export>
        <build_type condition="$ROS_VERSION == 1">colcon</build_type>
        <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
    </export>
</package>
